services:
  phpcsfixer.tool.command.handler:
    class: PhpGitHooks\Module\PhpCsFixer\Contract\CommandHandler\PhpCsFixerToolCommandHandler
    arguments: ["@php.cs.fixer.tool"]
    tags:
      - { name: bruli.command_handler, handles: \PhpGitHooks\Module\PhpCsFixer\Contract\Command\PhpCsFixerToolCommand }
