services:
  jsonlint.tool.command.handler:
    class: PhpGitHooks\Module\JsonLint\Contract\CommandHandler\JsonLintToolCommandHandler
    arguments: ["@jsonlint.tool"]
    tags:
     - { name: bruli.command_handler, handles: \PhpGitHooks\Module\JsonLint\Contract\Command\JsonLintToolCommand }
